date: time: 16/02/2021 13:57:08, exception type: AttributeError, full traceback: ['  File "/home/alex/OOP Hw/app.py", line 23, in <module>\n    models.candidate_one\n'], end= '
date: time: 16/02/2021 13:57:12, exception type: AttributeError, full traceback: ['  File "/home/alex/OOP Hw/app.py", line 23, in <module>\n    models.candidate_one\n'], end= '
date: time: 16/02/2021 13:59:07, exception type: AttributeError, full traceback: ['  File "/home/alex/OOP Hw/app.py", line 23, in <module>\n    models.candidate_one\n'], end= '
date: time: 16/02/2021 14:04:18, exception type: AttributeError,full traceback: ['  File "/home/alex/OOP Hw/app.py", line 17, in <module>\n    models.candidate_one\n'], end= 
date: time: 16/02/2021 14:05:29, exception type: AttributeError,full traceback: ['  File "/home/alex/OOP Hw/app.py", line 17, in <module>\n    models.candidate_one\n'], end= 
